development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "async") %>
  <% if ENV["REDIS_URL"].present? %>
  url: <%= ENV["REDIS_URL"] %>
  <% end %>
  channel_prefix: app_production
